ALTER TABLE "productLocations" ADD COLUMN "inGallery" BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE "productLocations" ADD COLUMN "spotlightOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "productLocations" ADD COLUMN "galleryOrder" INTEGER NOT NULL DEFAULT 0;
