language: node_js
before_script:
  - psql -c 'create database "goodybag-test";' -U postgres
  - psql -d "goodybag-test" -a -f db/fixtures/test.sql
env:
  - GB_ENV=test mode=test PG_CON="postgres://postgres@127.0.0.1/goodybag-test"
node_js:
  - 0.8
