language: node_js
before_script:
  - sudo cat /etc/postgresql/9.1/main/pg_hba.conf
  - echo "yes" | sudo add-apt-repository ppa:pitti/postgresql
  - sudo apt-get -y remove postgresql
  - sudo apt-get update -qq
  - sudo apt-get -q -y -o Dpkg::Options::=--force-confdef install postgresql-9.2
  - sudo chmod 777 /etc/postgresql/9.2/main/pg_hba.conf
  - sudo echo "local   all         all                               trust" > /etc/postgresql/9.2/main/pg_hba.conf
  - sudo echo "host    all         all         127.0.0.1/32          trust" >> /etc/postgresql/9.2/main/pg_hba.conf
  - sudo echo "host    all         all         ::1/128               trust" >> /etc/postgresql/9.2/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - sudo -u postgres psql -c "ALTER user postgres with password 'postgres';"
  - psql -c 'create database "goodybag-test";' -U postgres -w
env:
  - DEBIAN_FRONTEND=noninteractive GB_ENV=test PGPASSWORD=postgres PG_CON="postgres://postgres:postgres@127.0.0.1:5433/goodybag-test"
node_js:
  - 0.8
