language: node_js
env:
  - DEBIAN_FRONTEND=noninteractive GB_ENV=test PG_CON="postgres://djgmanhnnngynx:grAVcRvSoymDL0SUxeeKa2_CEJ@ec2-54-243-229-57.compute-1.amazonaws.com:5432/d6p6bdbqf16t00"
node_js:
  - 0.8
