language: node_js
before_script:
  - echo "yes" | sudo add-apt-repository ppa:pitti/postgresql
  - sudo apt-get -y --purge remove postgresql
  - sudo apt-get update -qq
  - sudo apt-get -q -y -o Dpkg::Options::=--force-confnew install postgresql-9.2
  - sudo echo "local   all         all                               trust" > /etc/postgresql/9.2/main/pg_hba.conf
  - psql -c 'create database "goodybag-test";' -h localhost -p 5433
env:
  - DEBIAN_FRONTEND=noninteractive GB_ENV=test PGPASSWORD=postgres PG_CON="postgres://127.0.0.1:5433/goodybag-test"
node_js:
  - 0.8
