language: node_js
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-9.2
  - psql -c 'create database "goodybag-test";' -U postgres
env:
  - GB_ENV=test PG_CON="postgres://postgres@127.0.0.1/goodybag-test"
node_js:
  - 0.8
