language: node_js
before_script:
#  - sudo cat /etc/postgresql/9.1/main/pg_hba.conf
#  - sudo cat /etc/postgresql/9.1/main/pg_ident.conf
#  - sudo cat /etc/postgresql/9.1/main/postgresql.conf
#  - echo "yes" | sudo add-apt-repository ppa:pitti/postgresql
#  - sudo apt-get -y remove postgresql
#  - sudo apt-get update -qq
#  - sudo apt-get -q -y -o Dpkg::Options::=--force-confdef install postgresql-9.2
  - sudo chmod 777 /etc/postgresql/9.1/main/pg_hba.conf
  - sudo echo "local   all         postgres                          trust" > /etc/postgresql/9.1/main/pg_hba.conf
  - sudo echo "local   all         all                               trust" >> /etc/postgresql/9.1/main/pg_hba.conf
  - sudo echo "host    all         all         127.0.0.1/32          trust" >> /etc/postgresql/9.1/main/pg_hba.conf
  - sudo echo "host    all         all         ::1/128               trust" >> /etc/postgresql/9.1/main/pg_hba.conf
  - sudo echo "host    all         all         0.0.0.0/0             trust" >> /etc/postgresql/9.1/main/pg_hba.conf
  - sudo echo "host    all         all         0.0.0.0 255.255.255.255 trust" >> /etc/postgresql/9.1/main/pg_hba.conf
  - node db
env:
  - DEBIAN_FRONTEND=noninteractive GB_ENV=test PG_CON="postgres://bwuurwsubmhlix:dHqObghON5g_hlqNzY88mRZi3w@ec2-54-243-229-57.compute-1.amazonaws.com:5432/d5os1j83m8otfk"
node_js:
  - 0.8
